language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: valaz-github
    token:
      secure: "$SONAR_TOKEN"
install: "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script: "./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent test -B -PskipNpm sonar:sonar
  -Dalpha_api_key='$ALPHA_API_KEY'"
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app:
    master: grafeo
    develop: grafeo-dev
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- openssl aes-256-cbc -K $encrypted_fb8c75fa2d2a_key -iv $encrypted_fb8c75fa2d2a_iv
  -in deploy.key.enc -out deploy.key -d
- chmod +x ./deploy.sh
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan dokku.valaz.ru >> ~/.ssh/known_hosts
- git remote add deploy dokku@dokku.valaz.ru:grafeo
- git remote add deploy-dev dokku@dokku.valaz.ru:grafeo-dev
- git config --global push.default simple
