language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: valaz-github
    token:
      secure: "$SONAR_TOKEN"
install: "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script: "./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent test -B -PskipNpm sonar:sonar"
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app:
    master: progressio
    develop: grafeo-dev
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
