jobs:
  include:
    - stage: server build
      language: java
      jdk: oraclejdk8
      addons:
        sonarcloud:
          organization: valaz-github
          token:
            secure: "$SONAR_TOKEN"
      before_install:
        - cd grafeo-server
      install:
        - mvn install -DskipTests=true -B
      script:
        - mvn test -B
      cache:
        directories:
          - "$HOME/.m2/repository"
          - "$HOME/.sonar/cache"
    - stage: web build
      language: node_js
      node_js: "10"
      before_install:
        - cd grafeo-web
      install:
        - npm install
      script:
        - npm run-script build
      cache:
        npm: true
        directories:
          - node_modules
    - stage: deploy
      script: skip
      language: bash
      deploy:
        provider: script
        script: bash .travis/deploy-mock.sh