jobs:
  include:
    # Build Java Server
    - stage: build
      language: java
      jdk: oraclejdk8
      addons:
        sonarcloud:
          organization: valaz-github
          token:
            secure: "$SONAR_SERVER_TOKEN"
      before_install:
        - cd grafeo-server
      install:
        - mvn install -DskipTests=true -B
      script:
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test -B sonar:sonar -Dsonar.projectKey=grafeo-server
      name: "Server build"
      cache:
        directories:
          - "$HOME/.m2/repository"
          - "$HOME/.sonar/cache"
    - script: npm run-script build
      name: "Web build"
      language: node_js
      node_js: "10"
      before_install:
        - cd grafeo-web
      install:
        - npm install
      cache:
        npm: true
        directories:
          - grafeo-web/node_modules
    # Deploy to Dev environment
    - stage: deploy to dev environment
      name: Deploing to dokku
      if: branch = dev AND type IN (push)
      script: skip
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_fb8c75fa2d2a_key -iv $encrypted_fb8c75fa2d2a_iv
          -in .travis/deploy.key.enc -out .travis/deploy.key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 .travis/deploy.key
        - ssh-add .travis/deploy.key
        - ssh-keyscan dokku.valiev.top >> ~/.ssh/known_hosts
      deploy:
        - provider: script
          script: bash .travis/deploy_grafeo-dev_all.sh
          on:
            branch: dev
      after_deploy:
        - sleep 15
        - curl https://dev.grafeo.pro
        - bash .travis/validate_grafeo-dev.sh || travis_terminate 1;
      language: bash
    # Deploy to Prod environment
    - stage: deploy to prod environment
      name: Deploing to dokku
      if: branch = master AND type IN (push)
      script: skip
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_fb8c75fa2d2a_key -iv $encrypted_fb8c75fa2d2a_iv
          -in .travis/deploy.key.enc -out .travis/deploy.key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 .travis/deploy.key
        - ssh-add .travis/deploy.key
        - ssh-keyscan dokku.valiev.top >> ~/.ssh/known_hosts
      deploy:
        - provider: script
          script: bash .travis/deploy_grafeo_all.sh
          on:
            branch: master
      after_deploy:
        - sleep 15
        - curl https://grafeo.pro
        - bash .travis/validate_grafeo.sh || travis_terminate 1;
      language: bash
