jobs:
  include:
    - stage: server build
      language: java
      jdk: oraclejdk8
      addons:
        sonarcloud:
          organization: valaz-github
          token:
            secure: "$SONAR_TOKEN"
      before_install:
        - cd grafeo-server
      install:
        - mvn install -DskipTests=true -B
      script:
        - mvn test -B
      cache:
        directories:
          - "$HOME/.m2/repository"
          - "$HOME/.sonar/cache"
    - stage: web build
      language: node_js
      node_js: "10"
      before_install:
        - cd grafeo-web
      install:
        - npm install
      script:
        - npm run-script build
      cache:
        npm: true
        directories:
          - grafeo-web/node_modules
    - stage: deploy dev
      if: branch IN (dev, master, monorepo)
      script: skip
      language: bash
      deploy:
        provider: script
        script: bash .travis/deploy-dev-mock.sh
    - stage: test dev
      if: branch IN (dev, master, monorepo)
      language: bash
      script: 'curl https://dev.grafeo.pro'
    - stage: deploy prod
      if: branch = master
      script: skip
      language: bash
      deploy:
        provider: script
        script: bash .travis/deploy-mock.sh
    - stage: test prod
      if: branch = master
      language: bash
      script: 'curl https://grafeo.pro'
