matrix:
  include:
    - language: java
      jdk: oraclejdk8
      addons:
        sonarcloud:
          organization: valaz-github
          token:
            secure: "$SONAR_TOKEN"
      before_script:
        - cd grafeo-server
      install:
        - mvn install -DskipTests=true -B
      script:
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test -B sonar:sonar
      cache:
        directories:
          - "$HOME/.m2/repository"
          - "$HOME/.sonar/cache"
    - language: node_js
      node_js: "10"
      before_script:
        - cd grafeo-web
      install:
        - npm install
      script:
        - npm run-script build


