jobs:
  include:
    - stage: server build
      language: java
      jdk: oraclejdk8
      addons:
        sonarcloud:
          organization: valaz-github
          token:
            secure: "$SONAR_TOKEN"
      before_install:
        - cd grafeo-server
      install:
        - mvn install -DskipTests=true -B
      script:
        - mvn test -B
      cache:
        directories:
          - "$HOME/.m2/repository"
          - "$HOME/.sonar/cache"
    - stage: web build
      language: node_js
      node_js: "10"
      before_install:
        - cd grafeo-web
      install:
        - npm install
      script:
        - npm run-script build
      cache:
        npm: true
        directories:
          - grafeo-web/node_modules
    - stage: deploy Web to dev
      if: branch IN (dev, monorepo)
      before_script:
        - openssl aes-256-cbc -K $encrypted_fb8c75fa2d2a_key -iv $encrypted_fb8c75fa2d2a_iv
          -in .travis/deploy.key.enc -out .travis/deploy.key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 .travis/deploy.key
        - ssh-add .travis/deploy.key
        - ssh-keyscan dokku.valiev.top >> ~/.ssh/known_hosts
        - git remote add grafeo-dev-web dokku@dokku.valiev.top:grafeo-dev-web
        - git config --global push.default simple
      script: bash .travis/deploy_grafeo-dev-web.sh
      language: bash
    - stage: deploy Server to dev
      if: branch IN (dev, monorepo)
      before_script:
        - openssl aes-256-cbc -K $encrypted_fb8c75fa2d2a_key -iv $encrypted_fb8c75fa2d2a_iv
          -in .travis/deploy.key.enc -out .travis/deploy.key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 .travis/deploy.key
        - ssh-add .travis/deploy.key
        - ssh-keyscan dokku.valiev.top >> ~/.ssh/known_hosts
        - git remote add grafeo-dev dokku@dokku.valiev.top:grafeo-dev
        - git config --global push.default simple
      script: bash .travis/deploy_grafeo-dev.sh
      language: bash
    - stage: test dev
      if: branch IN (dev, monorepo)
      language: bash
      script: 'curl https://dev.grafeo.pro'
    - stage: deploy prod
      if: branch = master
      script: skip
      language: bash
      deploy:
        provider: script
        script: bash .travis/deploy-mock.sh
        on:
          braches:
            only:
              - master
    - stage: test prod
      if: branch = master
      language: bash
      script: 'curl https://grafeo.pro'
