language: java
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: valaz-github
    token:
      secure: "$SONAR_TOKEN"
install: "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script: "./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent test -B -PskipNpm sonar:sonar"
deploy:
  provider: heroku
  api_key:
    secure: GMrOhI/kB0ACYKsrzcruSpn0s570lL9g7pCYFTKYDQvBoB8Mp6fS1/qmUK9jI4o3ycQX+4s/pbhh3iCgXVvQj7D27asUh2Snlu2hMgqjnka0xMUbIowlr4Xwrf01PTXB9Sn2Fi9wM7pv4LD05KQtQ5CPBdRpTpn4aWUPJ8C+9rGAid6HuJOHbaqpRnKsrtoHW8jwWWsXoroN4dd3qJoCejm8JGVIoEG7Jwf2REp54apIkhHKfzVgk++Bn5GUR9N7cknuu8q5YK3OnziJbWRnT9vtsY9ctYdsyYNtyKzsI1COq5fOpuamV+yMTw+944oHECl/mIoFWRAV+7YWrE1jvQOotp8BFnt7GYsH9otH3NXbfAnixpLYY0w4DM3vhA4NTzqNUwgGa4JqiW8aakuShx87gdS+52yvqqDFfblQQpJVj9qONKlHRq8BQx0OXIEjDccE3/bcT2N769dHSYIUNGW9mvUdA3DcUVW5RDqpu26wAZOpTwd0+hJ/M5c/+fgKs9MykdwG73BoQFgaI1eRlV5bYPuMfNpQdMDrf1w7nIyE0MkIngRJGra8PPdNTF8Ed+yCDCS8jD7njGt4QPg5eNZViY0ggjSMaDmS826K2Ot+8WYVzPsBWNv/G1rkkYQtfKAlqqGwUBnJACT3nqKXwqdaNuwbf/9JpMsiHK6X2O8=
  app:
    master: progressio
    develop: progressio-dev
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
