version: '3'
services:
    db:
        container_name: grafeo_db
        image: postgres:10.4
        volumes:
            - grafeo_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=sample
            - POSTGRES_USER=sample
            - POSTGRES_DB=sample
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    grafeo_db: {}