name: Build and Deploy

on:
  push:
    branches:
      - dev
      - master

jobs:
  server_build:
    name: Server Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd grafeo-server
          mvn --batch-mode --update-snapshots verify
  web_build:
    name: Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          cd grafeo-web
          yarn install
      - name: Generate build
        run: |
          cd grafeo-web
          yarn run build

  dev_deploy:
    needs: [ server_build, web_build ]
    if: github.ref == 'refs/heads/upgrade'
    name: Dev Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push Dev Web to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dale.valiev.top:22/grafeo-dev-web'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Push Dev Server to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dale.valiev.top:22/grafeo-dev-server'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  prod_deploy:
    needs: [ server_build, web_build ]
    if: github.ref == 'refs/heads/master'
    name: Prod Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push Prod Server to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dale.valiev.top:22/grafeo-prod-server'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Push Prod Web to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dale.valiev.top:22/grafeo-prod-web'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
